authors = ["Alejandro R. Mosteo"]
description = "Alex's Ada Assortment (of miscellaneous utilities)"
licenses = ["LGPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
name = "aaa"
version = "0.2.0"
