authors = ["Alejandro R. Mosteo"]
description = "Alex's Ada Assortment (of miscellaneous utilities)"
long-description = """
Alex's Ada Assortment of Utilities

- Text formatting (paragraphs, tables).
- Indefinite containers.
- Enumeration validity/conversions of string images.
- On-demand stack backtraces.
"""
licenses = ["LGPL 3.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
name = "aaa"
version = "0.2.1"
tags = ["miscellanea", "utility"]
